# Generated by Django 6.0.1 on 2026-03-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
